# Generated by Django 3.2.9 on 2021-12-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True)),
                ('taxa_dolar', models.FloatField()),
                ('taxa_real', models.FloatField()),
                ('taxa_iene', models.FloatField()),
                ('taxa_euro', models.FloatField()),
            ],
        ),
    ]
